server:
  listen: 8080
  workers: 4
  upstreams:
    - id: node1
      url: https://jsonplaceholder.typicodedafsdf.com
    - id: node2
      url: https://httpbin.org
  paths:
    - path: /posts/1
      upstreams:
        - node1
    - path: /anything/*
      upstreams:
        - node2
  headers:
    - key: X-Forwarded-For
      value: "$ip"
    - key: X-Gonx-Proxy
      value: "true"